### ISSUE TITLE
`_.url.appendParam()` 无法覆盖 URL 中已有的同名参数

### ISSUE THREAD

**Issue by cssmagic** [CMUI/underscore.ext#27]
```js
_.url.appendParam('http://abc.com/?b=1', {b: 2})
```

会得到 `'http://abc.com/?b=1&b=2'`，貌似不科学。

cc @zhanglin800

**Comment by cssmagic** [comment]
后来认为这是不是一个 bug，原有行为没有问题。因为：

* `http://abc.com/?b=1&b=2` 是一个合法的 URL。

* “Append” 的语义就是 “追加”。如果某个方法的功能是覆盖 URL 中已有的同名参数，那它不应叫作 `appendParam()`；应该由另一个 `updateParam()` 的方法来做这件事；或者繁琐一点，`parseQuery()` 之后修改参数值再序列化。

cc @z5

**Comment by z5** [comment]
是否需要一个upAppendParam的方法呢，哇哈哈。

**Comment by cssmagic** [comment]
可能会加 :smiley:
